name: Compilar DSi IA

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Nintendo DS
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20241104

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Comprobar devkitARM
        run: |
          echo "DEVKITPRO=$DEVKITPRO"
          echo "DEVKITARM=$DEVKITARM"
          test -f "$DEVKITARM/ds_rules"
          test -x "$DEVKITARM/bin/arm-none-eabi-g++"
          "$DEVKITARM/bin/arm-none-eabi-g++" --version

      - name: Compilar
        run: make V=1

      - name: Comprobar NDS
        run: |
          ls -lh
          test -f DSi-IA.nds
          echo "NDS generado correctamente."

      - name: Subir NDS
        uses: actions/upload-artifact@v4
        with:
          name: DSi-IA-NDS
          path: DSi-IA.nds
          if-no-files-found: error
